### ISSUE TITLE
SSL Error with das2py

### ISSUE THREAD

**Issue by BrieucCo** [das-developers/das2py#14] opened 2023-10-31 09:32 UTC
I'm having a problem with das2py it seems that I cannot reach any data on the server, when I try to reach any node (except iowa) I get the following message

src = das2.get_node('tag:das2.org,2012:site:/uiowa/juno')INFO: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

INFO: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/python37/lib/python3.7/das2/__init__.py", line 250, in get_node
    dDef = _das2.get_node(sPathId)
_das2.Error: Node U. Iowa (URI 'tag:das2.org,2012:site:/uiowa') has no child node that starts with juno
    (Reported from das2/node.c, line 539)

Surprisingly, src = das2.get_node('tag:das2.org,2012:site:/uiowa') doesnt return an error and in that case src['juno'].props returns

{'name': 'Juno',
 'title': 'Jupiter polar orbiter - Launch date 2011-08-05',
 'type': 'Catalog',
 'urls': ['http://das2.org/catalog/das/site/uiowa/juno.json'],
 '_path': 'tag:das2.org,2012:site:/uiowa/juno'}

If that can help I have this :

src.props

{'catalog': {'cassini': {'name': 'Cassini',
   'title': 'Saturn System Explorer - Orbit Insertion 2004-06-30',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/cassini.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/cassini'},
  'de': {'name': 'DE',
   'title': 'Earth polar orbiters - Launch date 1981-08-03',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/de.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/de'},
  'earth': {'name': 'Earth',
   'title': 'Earth based observatories',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/earth.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/earth'},
  'galileo': {'name': 'Galileo',
   'title': 'Jupiter equatorial orbiter - Launch date 1989-10-13',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/galileo.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/galileo'},
  'isee': {'name': 'ISEE',
   'title': 'International Sun-Earth Explorers - Launch date 1977-10-22',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/isee.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/isee'},
  'juno': {'name': 'Juno',
   'title': 'Jupiter polar orbiter - Launch date 2011-08-05',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/juno.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/juno'},
  'mars_express': {'name': 'Mars Express',
   'title': 'Mars polar orbiter - Launch date 2003-06-02',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/mars_express.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/mars_express'},
  'maven': {'name': 'Maven',
   'title': 'Mars Atmosphere and Volatile Evolution Mission - Orbit Insertion 2014-09-22',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/maven.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/maven'},
  'stereo': {'name': 'Stereo',
   'title': 'Dual Solar Terrestrial Relation Observatories - Launch date 2006-10-26',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/stereo.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/stereo'},
  'van_allen_probes': {'name': 'Van Allen Probes',
   'title': "Twin probes of the Earth's inner and outer radiation belts, launched on 2012-08-30",
   'type': 'Catalog',
   'urls': ['https://emfisis.physics.uiowa.edu/~cwp/van_allen_probes.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/van_allen_probes'},
  'voyager': {'name': 'Voyager',
   'title': 'Dual Spacecraft Mission to the Outer Planets, and Beyond',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/voyager.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/voyager'},
  'wind': {'name': 'Wind',
   'title': 'WIND Solar-Terrestrial Mission  - Launch date 1994-11-01',
   'type': 'Catalog',
   'urls': ['http://das2.org/catalog/das/site/uiowa/wind.json'],
   '_path': 'tag:das2.org,2012:site:/uiowa/wind'}},
 'name': 'U. Iowa',
 'title': 'University of Iowa, Department of Physics and Astronomy',
 'type': 'Catalog',
 'version': '0.4',
 '_url': 'https://raw.githubusercontent.com/das-developers/das-cat/master/cat/das/site/uiowa.json',
 '_path': 'tag:das2.org,2012:site:/uiowa'}

I try to update das2 numpy and spacepy but thats didn't help.

Maybe it is related to the fact that when I want to edit the url of a plot (from Juno data) on a saved vap file on autoplot I have this
![image](https://github.com/das-developers/das2py/assets/105926322/1e688012-945e-4740-8ce2-58f0b77415a3)

However, I managed to fix this by changing the adress with https instead of http.

**Comment by cpiker** [comment] 2023-10-31 16:19
It turns out this was actually caused by bugs in: 

1.  [das2C](https://github.com/das-developers/das2C), which is wrapped by das2py, and 
2. [das-cat](https://github.com/das-developers/das-cat), which provides a backup federated catalog root

The most important bug is that port 80 was being used to connect to SSL in instances where the server redirected http to https.  Since the data out of port 80 certainly doesn't look like a TLS handshake the openssl libraries issued a wrong TLS version number issue.

The second bug was that the federated catalog mirror contained http links to U. Iowa servers, which is incorrect, but a lesser  issue.

The latest release of das2C and das-cat corrects the issues.  

We'll leave this bug open here until new anaconda of das2py is generated, since it will close the issue for most users.

**Comment by cpiker** [comment] 2023-11-10 20:55
Building against das2C tags/v2.3.0 fixes the issue.

**Closed as completed by cpiker** 2023-11-10 20:55 UTC

**Comment by BrieucCo** [comment] 2023-11-16 13:59
I think it's still doesn't work on my version of das2. It might be because anaconda only see version 2.3.1 and not the new 2.3.0 ?
